### PR TITLE
compile using babel

### PR DESCRIPTION
**Pull request by xaiki**
this makes it possible to use tglib out of npm without a fully functional es7 setup

Signed-off-by: Niv Sardi <xaiki@evilgiggle.com>

### CODE REVIEW

**Comment by xaiki** [comment]
note that it lacks shipping binaries/rebuilding for each platform

**Comment by nodegin** [comment]
Hi, thanks for the PR. I am not quite understand what do you mean by "out of npm", can you provide an actual use case for this PR?

**Comment by xaiki** [comment]
sorry just seeing your comments,
with this PR you can just `npm install tglib` and start using the app in any project, i.e. you don't require a fully funcional es7 setup.

**Comment by nodegin** [comment]
Hello, I see. Can you fix the conflicts to allow me publish the update?

**Comment by xaiki** [comment]
refreshed

**Pull request merged**
